services:
  bot:
    build: .
    volumes:
      - .:/code
    env_file: .env
    restart: unless-stopped
  #   depends_on:
  #     - influxdb

  # influxdb:
  #   image: influxdb:2.0
  #   env_file: .env
  #   # environment:
  #   #   - "DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}"
  #   #   - "DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}"
  #   #   - "DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}"
  #   #   - "DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}"
  #   #   - "DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}"
  #   #   - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
  #   volumes:
  #     - ./data:/var/lib/influxdb2
  #     - ./config:/etc/influxdb2
  #   ports:
  #     - 8086:8086
  #   restart: unless-stopped